### ISSUE TITLE
O jogo crasha ao instalar a tradução

### ISSUE THREAD

**Issue by LucasZiion** [pobruno/Pathway-traducao-ptbr#2]
ele da esse erro aqui, aalguem pode me ajudar?
o jogo simplesmente fecha com a tradução... quando eu coloco os arquivos originais o jogo abre normalmente!

java.lang.RuntimeException: Exception thrown during execution of asynchronous task!
	at com.badlogic.gdx.concurrent.AsyncTask.await(AsyncTask.java:105)
	at com.robotality.pulp.game.screens.AsyncLoaderScreen.await(AsyncLoaderScreen.java:186)
	at com.robotality.pulp.game.screens.AssetLoaderScreen.update(AssetLoaderScreen.java:165)
	at com.robotality.game.screens.GameScreenAdapter.update(GameScreenAdapter.java:134)
	at com.robotality.pulp.PulpHeroAdapter.update(PulpHeroAdapter.java:92)
	at com.robotality.game.loop.FixedTimeStepGameLoop.render(FixedTimeStepGameLoop.java:48)
	at com.robotality.game.adapter.GameApplicationAdapter.render(GameApplicationAdapter.java:151)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:335)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.renderThreadFunction(Lwjgl3Application.java:205)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.badlogic.gdx.utils.GdxRuntimeException: No master language code found: -405211242
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.badlogic.gdx.concurrent.AsyncTask.await(AsyncTask.java:90)
	... 9 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: No master language code found: -405211242
	at com.robotality.game.i18n.LanguageTable.onJsonRead(LanguageTable.java:79)
	at com.robotality.game.i18n.LanguageTable.refresh(LanguageTable.java:107)
	at com.robotality.game.i18n.LanguageTable.read(LanguageTable.java:268)
	at com.robotality.pulp.i18n.I18N.reload(I18N.java:59)
	at com.robotality.pulp.i18n.I18N.<init>(I18N.java:32)
	at com.robotality.pulp.game.PulpHero.lambda$initializeGameAssets$1(PulpHero.java:334)
	at com.robotality.game.util.DeferredRunnable.execute(DeferredRunnable.java:35)
	at com.robotality.game.util.TimedRunnable.execute(TimedRunnable.java:33)
	at com.robotality.game.util.TimedRunnable.<init>(TimedRunnable.java:21)
	at com.robotality.pulp.game.PulpHero.initializeGameAssets(PulpHero.java:333)
	at com.robotality.pulp.game.screens.AssetLoaderScreen$Job.load(AssetLoaderScreen.java:57)
	at com.robotality.pulp.game.screens.AsyncLoaderScreen$Job.call(AsyncLoaderScreen.java:199)
	at com.robotality.pulp.game.screens.AsyncLoaderScreen$Job.call(AsyncLoaderScreen.java:195)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more

**Comment by kelciojr** [comment]
Cara, acontecia o mesmo comigo. Oq eu entendi é que o jogo não conseguia ler a linguagem. Como se algum parametro da linguagem não batesse com  codigo do jogo. To falando de uma forma bem leiga. Abri os arquivos no VS code e o arquivo config tem que ser o original que ja veio no jogo, para qualquer lingua que quiser colocar. Então você só cola na pasta da linguagem os outros 8 arquivos. que da certo, deu no meu.
![image](https://github.com/PoBruno/Pathway-traducao-ptbr/assets/45525013/9c50d337-2cf0-4e64-90ca-c1b98179110f)

**Comment by kelciojr** [comment]
Apenas com os outros arquivos em portugues, ele traduz certinho
![image](https://github.com/PoBruno/Pathway-traducao-ptbr/assets/45525013/e5b8df66-17fc-4f8b-bc1a-e97b88e40ee5)

**Comment by kelciojr** [comment]
![image](https://github.com/PoBruno/Pathway-traducao-ptbr/assets/45525013/ab5590d5-6f54-4e79-9efa-5990b746fa7d)

**Comment by LucasZiion** [comment]
> Cara, acontecia o mesmo comigo. Oq eu entendi é que o jogo não conseguia ler a linguagem. Como se algum parametro da linguagem não batesse com codigo do jogo. To falando de uma forma bem leiga. Abri os arquivos no VS code e o arquivo config tem que ser o original que ja veio no jogo, para qualquer lingua que quiser colocar. Então você só cola na pasta da linguagem os outros 8 arquivos. que da certo, deu no meu. ![image](https://private-user-images.githubusercontent.com/45525013/328717828-9c50d337-2cf0-4e64-90ca-c1b98179110f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzUyNjMsIm5iZiI6MTcxNTg3NDk2MywicGF0aCI6Ii80NTUyNTAxMy8zMjg3MTc4MjgtOWM1MGQzMzctMmNmMC00ZTY0LTkwY2EtYzFiOTgxNzkxMTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1NTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNzFkNTRkZDAyZTRjYjJjMDVlMmNhNjdkZTY5YmYwNDNmYjVkNmQ2ZjM4NmQ4NDgwOGVlZWYyMmMyZGM2ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qsJVKImPFRCffftRIJxwoea5UCgWka8EEt6ixc0rVsU)

Ae irmão, caraca te amo muito. valeu mesmo de coração! depois de "anos" tentando jogar esse jogo, agora vou poder, graças a você, você é iluminado, ja tinha ate perdido as esperanças de alguém respondendo minha mensagem aqui, valeu mesmo irmão, que Deus te abençoe!

**Comment by kelciojr** [comment]
Tamo junto kkk Eu só queria aprender era a traduzir, sei nem pra onde vai

**Comment by PoBruno** [comment]
> Cara, acontecia o mesmo comigo. Oq eu entendi é que o jogo não conseguia ler a linguagem. Como se algum parametro da linguagem não batesse com codigo do jogo. To falando de uma forma bem leiga. Abri os arquivos no VS code e o arquivo config tem que ser o original que ja veio no jogo, para qualquer lingua que quiser colocar. Então você só cola na pasta da linguagem os outros 8 arquivos. que da certo, deu no meu. ![image](https://private-user-images.githubusercontent.com/45525013/328717828-9c50d337-2cf0-4e64-90ca-c1b98179110f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1NjcxODgsIm5iZiI6MTcxODU2Njg4OCwicGF0aCI6Ii80NTUyNTAxMy8zMjg3MTc4MjgtOWM1MGQzMzctMmNmMC00ZTY0LTkwY2EtYzFiOTgxNzkxMTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDE5NDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMWI1MTU3MzkzYWQyZDViN2UxMmU5ZTBlMWViNzM1ODM3YzQ4Yzc3MmUwYzU2YWRkYmU1MjM2YTZlYjBjNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1Udh_0CRR8HHgbvYZGBn8T4Rowls-i0ujedKAT_Qi7Q)

Perfeito, foi um erro meu, como eu desenvolvi o repositorio para a steam workshop, os desenvolvedores fazem com que seja possivel adicionar uma nova lingua no jogo baseado nesse arquivo de config, porém isso só funciona com o Workshop Steam, se adicionar manual os arquivos de tradução, o arquivo de config contendo a informações da lingua, só pode ser as linguas originais do jogo, quando adicionado o mod pelo workshop steam ele adiciona uma nova linguagem e então esse arquivo config com linguagem "pt-BR" acaba funcionando porque houve um "cadastro" da lingua "pt-BR". Vou criar uma pasta nova sem esse arquivo de config para o pessoal não se confundir.

Valeu pela ajuda!

Obrigado @LucasZiion 
@kelciojr desculpe não ter consiguido ajudar a tempo, mas a comunidade é boa demais e se ajuda sozinha!

**Comment by PoBruno** [comment]
fix #2 

# Problema
- Inicialmente o repositorio do projeto foi realizado como mod para Workshop Steam, onde o tem algun nível de integração entre a plataforma Steam e o Jogo, dessa maneira os desenvolvedores do jogo fazem com que seja possivel definir uma nova informação de Linguagem no arquivo de config e o jogo "adiciona" como um novo idioma para o jogo. 
- Se realizar o processo de intralação manual da Tradução, substituindo os arquivos, o processo de "adicionar" um novo idioma não é possivel.
- O arquivo de config do Idioma está com configurações de uma nova linguagem para o jogo `pt-BR` e dessa maneira ocorre erro no jogo porque ele não encontra a referencia da configuração de Idioma.

# Solução
- Excluir o **_config.json**
- Arquivo _config.json com valores `pt-BR` só funciona instalando o mod pelo Steam Workshop

# Fix #2 
- Arquivo _config.json excluido da pasta [pt-BR](https://github.com/PoBruno/Pathway-traducao-ptbr/tree/main/pt-BR)

**Comment by kelciojr** [comment]
Que é isso, foi uma experiência. Tô começando a entrar no mundo da programação e queria até saber como traduzir um jogo, achar os arquivos e texto e ir traduzindo. Então se tiver alguma dica de como posso começar eu gostaria de saber, gosto de conhecer como as coisas funcionam e qual o significado e importância de cada coisa

**Comment by PoBruno** [comment]
> Que é isso, foi uma experiência. Tô começando a entrar no mundo da programação e queria até saber como traduzir um jogo, achar os arquivos e texto e ir traduzindo. Então se tiver alguma dica de como posso começar eu gostaria de saber, gosto de conhecer como as coisas funcionam e qual o significado e importância de cada coisa

Legal @kelciojr, se quiser me adicionar no discord [@Lorthe.] e podemos trocar algumas experiencias e fazer algum novo projeto.
